-- Удаление таблиц, которые зависят от других таблиц
DROP TABLE IF EXISTS "VIEWS" CASCADE;
DROP TABLE IF EXISTS "ORDERS" CASCADE;
DROP TABLE IF EXISTS "USER_ROLES" CASCADE;
DROP TABLE IF EXISTS "TRANSACTIONS" CASCADE;
DROP TABLE IF EXISTS "WALLETS" CASCADE;
DROP TABLE IF EXISTS "SITES" CASCADE;

-- Удаление таблиц, которые не зависят от других таблиц
DROP TABLE IF EXISTS "LOG_MESSAGES" CASCADE;
DROP TABLE IF EXISTS "ROLES" CASCADE;
DROP TABLE IF EXISTS "TRANSACTION_TYPES" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;